### ISSUE TITLE
Key to reset rotation angle of map

### ISSUE THREAD

**Issue by zaher** [palestar/darkspace#16]
This Feature Request to add a key when clicked resets the rotation map angle, It is good for who always confused by names like me, or guiding newbies players.

**Comment by BlackYoup** [comment]
That's a good idea :)

Do you have an idea of the shortcut for that ?

**Comment by zaher** [comment]
What about ALT+R?

**Comment by UnspokenVoice** [comment]
ALT+R isnt currently used for anything else. should be a good choice.

**Comment by BlackYoup** [comment]
ALT doesn't seem to be a common used key for shortcuts. What about SHIFT+R ?

In any case, I made a first implementation of the feature [here](https://github.com/BlackYoup/darkspace/commit/5d1d7912de3456cc08f7235e3392426e91f725ad), I just need to figure out an icon for the button now. I'm open to any suggestions :)
